import esbuild from "esbuild";
import { readFileSync } from "node:fs";
import { builtinModules } from "node:module";
import process from "process";

const pkg = JSON.parse(readFileSync(new URL("./package.json", import.meta.url), "utf8"));

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
K-Tech Vault Atlas ${pkg.version}
*/
`;

const prod = process.argv[2] === "production";

const nodeBuiltins = [
  ...builtinModules,
  ...builtinModules.map((moduleName) => `node:${moduleName}`),
];

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...nodeBuiltins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  drop: prod ? ["console", "debugger"] : [],
  outfile: "main.js",
});

if (prod) {
  await context.rebuild();
  process.exit(0);
}

await context.watch();
