/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => VaultAtlasPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/funding.ts
var import_obsidian = require("obsidian");

// src/constants.ts
var PLUGIN_NAME = "K-Tech Vault Atlas";
var FUNDING_URL = "https://buymeacoffee.com/k_tech_studio";
function openBuyMeACoffee() {
  window.open(FUNDING_URL, "_blank");
}

// src/funding.ts
function isJa() {
  return String((0, import_obsidian.getLanguage)() || "").toLowerCase().startsWith("ja");
}
var FundingModal = class extends import_obsidian.Modal {
  constructor(app, kind, version) {
    super(app);
    this.kind = kind;
    this.version = version;
  }
  onOpen() {
    const { contentEl, titleEl } = this;
    titleEl.setText(PLUGIN_NAME);
    const heading = isJa() ? this.kind === "install" ? "\u30A4\u30F3\u30B9\u30C8\u30FC\u30EB\u3042\u308A\u304C\u3068\u3046\u3054\u3056\u3044\u307E\u3059" : `${this.version} \u3078\u66F4\u65B0\u3055\u308C\u307E\u3057\u305F` : this.kind === "install" ? "Thanks for installing!" : `Updated to ${this.version}`;
    contentEl.createEl("h3", { text: heading });
    contentEl.createEl("p", {
      text: isJa() ? this.kind === "install" ? "Vault \u306E\u30D5\u30A9\u30EB\u30C0\u3068 HUB \u3092\u8A3A\u65AD\u3057\u307E\u3059\u3002\u5F79\u306B\u7ACB\u3063\u305F\u3089\u30B5\u30DD\u30FC\u30C8\u3092\u304A\u9858\u3044\u3057\u307E\u3059\u3002" : "\u65B0\u3057\u3044\u7248\u306B\u66F4\u65B0\u3055\u308C\u307E\u3057\u305F\u3002\u958B\u767A\u306E\u52B1\u307F\u306B\u306A\u308A\u307E\u3059\u3002" : this.kind === "install" ? "Vault Atlas scans folder and hub structure before you reorganize. If it helps, consider supporting development." : "Thanks for updating. Your support keeps Vault Atlas improving."
    });
    const actions = contentEl.createDiv({ cls: "modal-button-container" });
    const coffeeBtn = actions.createEl("button", {
      cls: "mod-cta",
      text: "Buy Me a Coffee"
    });
    coffeeBtn.addEventListener("click", () => {
      window.open(FUNDING_URL, "_blank");
      this.close();
    });
    const laterBtn = actions.createEl("button", {
      text: isJa() ? "\u3042\u3068\u3067" : "Maybe later"
    });
    laterBtn.addEventListener("click", () => this.close());
  }
  onClose() {
    this.contentEl.empty();
  }
};
function openFundingModal(app, kind, version) {
  new FundingModal(app, kind, version).open();
}

// src/scan/report.ts
var SEVERITY_ICON = {
  info: "\u2705",
  warn: "\u26A0\uFE0F",
  gap: "\u2753"
};
function formatReportMarkdown(result) {
  const lines = [
    "# Vault Atlas Report",
    "",
    `Generated: ${result.generatedAt}`,
    `Vault: ${result.vaultName}`,
    "",
    "## Summary",
    `- Folders scanned: ${result.foldersScanned}`,
    `- Hubs found: ${result.hubCount}`,
    `- Needs decision: ${result.needsDecision}`,
    "",
    "## Findings",
    ""
  ];
  for (const finding of result.findings) {
    const icon = SEVERITY_ICON[finding.severity];
    lines.push(`${icon} ${finding.message}`);
    if (finding.detail) {
      lines.push(`   ${finding.detail}`);
    }
  }
  if (result.findings.length === 0) {
    lines.push("_No findings._");
  }
  lines.push("");
  return lines.join("\n");
}

// src/scan/vault-scan.ts
var import_obsidian2 = require("obsidian");

// src/profile.ts
var DEFAULT_VAULT_PROFILE = {
  version: 1,
  entryNotePath: "Home.md",
  hubTypeProperty: "type",
  hubTypeValue: "hub",
  hubNaming: "flexible",
  excludeFolderPrefixes: [".obsidian/", ".cursor/", "node_modules/"],
  dailyFolderPattern: "00 Inbox/Daily/",
  confirmedAt: ""
};
function normalizeFolderPath(path) {
  const trimmed = path.replace(/^\/+/, "").replace(/\\/g, "/");
  return trimmed.endsWith("/") ? trimmed : `${trimmed}/`;
}
function isExcludedFolder(folderPath, profile) {
  const normalized = normalizeFolderPath(folderPath);
  if (profile.dailyFolderPattern && normalized.startsWith(normalizeFolderPath(profile.dailyFolderPattern))) {
    return true;
  }
  return profile.excludeFolderPrefixes.some(
    (prefix) => normalized.startsWith(normalizeFolderPath(prefix))
  );
}
function mergeVaultProfile(stored) {
  var _a;
  if (!stored || stored.version !== 1) {
    return { ...DEFAULT_VAULT_PROFILE };
  }
  return {
    ...DEFAULT_VAULT_PROFILE,
    ...stored,
    version: 1,
    excludeFolderPrefixes: (_a = stored.excludeFolderPrefixes) != null ? _a : DEFAULT_VAULT_PROFILE.excludeFolderPrefixes
  };
}

// src/scan/hub-detect.ts
var FRONTMATTER_RE = /^---\n([\s\S]*?)\n---/;
function parseFrontmatter(content) {
  const match = FRONTMATTER_RE.exec(content);
  if (!match) {
    return {};
  }
  const result = {};
  for (const line of match[1].split("\n")) {
    const colon = line.indexOf(":");
    if (colon === -1) {
      continue;
    }
    const key = line.slice(0, colon).trim();
    let value = line.slice(colon + 1).trim();
    if (value.startsWith('"') && value.endsWith('"') || value.startsWith("'") && value.endsWith("'")) {
      value = value.slice(1, -1);
    }
    result[key] = value;
  }
  return result;
}
function isHubNote(content, profile) {
  const fm = parseFrontmatter(content);
  return fm[profile.hubTypeProperty] === profile.hubTypeValue;
}

// src/scan/vault-scan.ts
function listMarkdownInFolder(folder) {
  return folder.children.filter(
    (child) => child instanceof import_obsidian2.TFile && child.extension === "md"
  );
}
function collectFolders(root, profile) {
  const folders = [];
  const walk = (folder) => {
    if (isExcludedFolder(folder.path ? `${folder.path}/` : "", profile)) {
      return;
    }
    folders.push(folder);
    for (const child of folder.children) {
      if (child instanceof import_obsidian2.TFolder) {
        walk(child);
      }
    }
  };
  walk(root);
  return folders;
}
async function scanVault(app, profile) {
  const findings = [];
  const root = app.vault.getRoot();
  const folders = collectFolders(root, profile);
  const entryFile = app.vault.getAbstractFileByPath(profile.entryNotePath);
  if (entryFile instanceof import_obsidian2.TFile) {
    findings.push({
      severity: "info",
      code: "ENTRY_FOUND",
      message: `\u5165\u53E3\u30CE\u30FC\u30C8: ${profile.entryNotePath}`,
      path: profile.entryNotePath
    });
  } else {
    findings.push({
      severity: "gap",
      code: "ENTRY_MISSING",
      message: `\u5165\u53E3\u30CE\u30FC\u30C8\u304C\u898B\u3064\u304B\u308A\u307E\u305B\u3093: ${profile.entryNotePath}`,
      path: profile.entryNotePath
    });
  }
  let hubCount = 0;
  let needsDecision = 0;
  for (const folder of folders) {
    const folderPath = folder.path;
    const prefix = folderPath ? `${folderPath}/` : "";
    if (isExcludedFolder(prefix, profile)) {
      continue;
    }
    const mdFiles = listMarkdownInFolder(folder);
    const hubFiles = [];
    for (const file of mdFiles) {
      const content = await app.vault.read(file);
      if (isHubNote(content, profile)) {
        hubFiles.push(file);
      }
    }
    if (hubFiles.length > 0) {
      hubCount += hubFiles.length;
      if (hubFiles.length > 1) {
        needsDecision += 1;
        findings.push({
          severity: "warn",
          code: "HUB_MULTIPLE",
          message: `HUB \u304C\u8907\u6570: ${folderPath || "(root)"}`,
          path: folderPath,
          detail: hubFiles.map((f) => f.path).join(", ")
        });
      }
      continue;
    }
    const noteCount = mdFiles.length;
    const subfolderCount = folder.children.filter(
      (c) => c instanceof import_obsidian2.TFolder
    ).length;
    if (noteCount === 0 && subfolderCount === 0) {
      continue;
    }
    if (noteCount >= 2 || subfolderCount > 0) {
      needsDecision += 1;
      findings.push({
        severity: "gap",
        code: "HUB_MISSING",
        message: `HUB \u306A\u3057\uFF08\u8981\u5224\u65AD\uFF09: ${folderPath || "(root)"} \u2014 md:${noteCount}, subfolders:${subfolderCount}`,
        path: folderPath
      });
    }
  }
  return {
    generatedAt: (/* @__PURE__ */ new Date()).toISOString(),
    vaultName: app.vault.getName(),
    foldersScanned: folders.length,
    hubCount,
    needsDecision,
    findings
  };
}

// src/settings.ts
var import_obsidian3 = require("obsidian");
var VaultAtlasSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.activeTab = "profile";
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.addClass("vault-atlas-settings");
    this.renderTabNav(containerEl);
    const panel = containerEl.createDiv({ cls: "vault-atlas-settings-panel" });
    this.renderActiveTab(panel);
  }
  hide() {
    this.containerEl.empty();
  }
  renderTabNav(containerEl) {
    const nav = containerEl.createDiv({ cls: "vault-atlas-settings-nav" });
    const tabs = [
      { id: "profile", label: "Profile" },
      { id: "support", label: "Support" }
    ];
    for (const tab of tabs) {
      const btn = nav.createEl("button", {
        cls: "vault-atlas-settings-tab",
        text: tab.label,
        type: "button"
      });
      if (tab.id === this.activeTab) {
        btn.addClass("is-active");
      }
      btn.addEventListener("click", () => {
        this.activeTab = tab.id;
        this.display();
      });
    }
  }
  renderActiveTab(panel) {
    switch (this.activeTab) {
      case "profile":
        this.renderProfileTab(panel);
        break;
      case "support":
        this.renderSupportTab(panel);
        break;
    }
  }
  profile() {
    return this.plugin.settings.vaultProfile;
  }
  async saveProfile(patch) {
    this.plugin.settings.vaultProfile = {
      ...this.plugin.settings.vaultProfile,
      ...patch
    };
    await this.plugin.saveSettings();
  }
  renderProfileTab(containerEl) {
    containerEl.createEl("p", {
      text: "Vault \u3054\u3068\u306E HUB \u5224\u5B9A\u30EB\u30FC\u30EB\u3002\u30B9\u30AD\u30E3\u30F3\u524D\u306B\u5408\u308F\u305B\u3066\u304F\u3060\u3055\u3044\u3002",
      cls: "setting-item-description"
    });
    const profile = this.profile();
    new import_obsidian3.Setting(containerEl).setName("Entry note path").setDesc("\u5165\u53E3\u30CE\u30FC\u30C8\uFF08\u4F8B: Home.md\uFF09").addText(
      (text) => text.setPlaceholder("Home.md").setValue(profile.entryNotePath).onChange(async (value) => {
        await this.saveProfile({ entryNotePath: value.trim() });
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Hub type property").setDesc("HUB \u5224\u5B9A frontmatter \u30AD\u30FC").addText(
      (text) => text.setValue(profile.hubTypeProperty).onChange(async (value) => {
        await this.saveProfile({ hubTypeProperty: value.trim() });
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Hub type value").setDesc("HUB \u3068\u307F\u306A\u3059\u5024").addText(
      (text) => text.setValue(profile.hubTypeValue).onChange(async (value) => {
        await this.saveProfile({ hubTypeValue: value.trim() });
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Daily folder pattern").setDesc("HUB \u4E0D\u8981\u5019\u88DC\uFF08\u4F8B: 00 Inbox/Daily/\uFF09\u3002\u7A7A\u6B04\u3067\u7121\u52B9\u3002").addText(
      (text) => {
        var _a;
        return text.setPlaceholder("00 Inbox/Daily/").setValue((_a = profile.dailyFolderPattern) != null ? _a : "").onChange(async (value) => {
          const trimmed = value.trim();
          await this.saveProfile({
            dailyFolderPattern: trimmed.length > 0 ? trimmed : null
          });
        });
      }
    );
    new import_obsidian3.Setting(containerEl).setName("Exclude folder prefixes").setDesc("1\u884C1\u4EF6\u3002\u30B9\u30AD\u30E3\u30F3\u304B\u3089\u9664\u5916\uFF08\u672B\u5C3E / \u63A8\u5968\uFF09").addTextArea((area) => {
      area.setValue(profile.excludeFolderPrefixes.join("\n")).onChange(async (value) => {
        await this.saveProfile({
          excludeFolderPrefixes: value.split("\n").map((line) => line.trim()).filter(Boolean)
        });
      });
      area.inputEl.rows = 4;
    });
  }
  renderSupportTab(containerEl) {
    containerEl.createEl("p", {
      text: "Vault Atlas \u306F\u30ED\u30FC\u30AB\u30EB\u306E\u307F\u3067\u52D5\u4F5C\u3057\u307E\u3059\u3002\u30CD\u30C3\u30C8\u30EF\u30FC\u30AF\u9001\u4FE1\u306F\u3042\u308A\u307E\u305B\u3093\u3002",
      cls: "setting-item-description"
    });
    new import_obsidian3.Setting(containerEl).setName("Support").setHeading();
    new import_obsidian3.Setting(containerEl).setName("Buy Me a Coffee").setDesc("K-Tech Studio \u306E\u958B\u767A\u3092\u652F\u63F4\u3059\u308B\uFF08\u4EFB\u610F\uFF09").addButton(
      (button) => button.setButtonText("Buy Me a Coffee").onClick(() => {
        openBuyMeACoffee();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Version").setDesc("\u30A4\u30F3\u30B9\u30C8\u30FC\u30EB\u4E2D\u306E\u7248").addText((text) => {
      text.setValue(this.plugin.manifest.version).setDisabled(true);
    });
  }
};

// src/storage.ts
function parseStorage(raw) {
  if (!raw || typeof raw !== "object") {
    return { vaultProfile: { ...DEFAULT_VAULT_PROFILE } };
  }
  const data = raw;
  if ("vaultProfile" in data) {
    return {
      vaultProfile: mergeVaultProfile(
        data.vaultProfile
      ),
      lastSeenVersion: typeof data.lastSeenVersion === "string" ? data.lastSeenVersion : void 0
    };
  }
  return {
    vaultProfile: mergeVaultProfile(data),
    lastSeenVersion: void 0
  };
}
function toStorage(vaultProfile, lastSeenVersion) {
  return { vaultProfile, lastSeenVersion };
}

// src/main.ts
var ReportModal = class extends import_obsidian4.Modal {
  constructor(app, markdown) {
    super(app);
    this.markdown = markdown;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("vault-atlas-report");
    contentEl.createEl("h2", { text: "Vault Atlas Report" });
    const pre = contentEl.createEl("pre");
    pre.textContent = this.markdown;
  }
  onClose() {
    this.contentEl.empty();
  }
};
var VaultAtlasPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.settings = parseStorage(void 0);
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new VaultAtlasSettingTab(this.app, this));
    this.addCommand({
      id: "run-vault-scan",
      name: "Run vault scan",
      callback: () => {
        void this.runScan();
      }
    });
    this.addRibbonIcon("map", "Vault Atlas: Run scan", () => {
      void this.runScan();
    });
    this.app.workspace.onLayoutReady(() => {
      void this.maybeShowFundingModal();
    });
  }
  async runScan() {
    try {
      const result = await scanVault(this.app, this.settings.vaultProfile);
      const markdown = formatReportMarkdown(result);
      new ReportModal(this.app, markdown).open();
      new import_obsidian4.Notice(
        `Vault Atlas: ${result.needsDecision} item(s) need decision, ${result.hubCount} hub(s) found.`
      );
    } catch (error) {
      const message = error instanceof Error ? error.message : "Unknown scan error";
      new import_obsidian4.Notice(`Vault Atlas scan failed: ${message}`);
    }
  }
  async loadSettings() {
    const storage = parseStorage(await this.loadData());
    this.settings = storage;
    this.lastSeenVersion = storage.lastSeenVersion;
  }
  async saveSettings() {
    await this.saveData(
      toStorage(this.settings.vaultProfile, this.lastSeenVersion)
    );
  }
  async maybeShowFundingModal() {
    const currentVersion = this.manifest.version;
    if (this.lastSeenVersion === currentVersion) {
      return;
    }
    const kind = this.lastSeenVersion ? "update" : "install";
    window.setTimeout(() => {
      openFundingModal(this.app, kind, currentVersion);
    }, 800);
    this.lastSeenVersion = currentVersion;
    await this.saveSettings();
  }
};
